### ISSUE TITLE
Reframe initial observation

### ISSUE THREAD

**Issue by hardie** [stackevo/endpoint-draft#2]
The draft currently says:

"We observe that this principle can only be applied, however, when one has agreement on what an endpoint is. Early in the design of the Internet, this agreement was relatively obvious: a network-layer endpoint was synonymous with a host, and a transport-layer endpoint was synonymous with a process running on a host.

The architecture of the Internet is necessarily descriptive. It should be as simple as possible but not simpler. Changes in the Internet through several decades of development and changing deployment models requires re-evaluating assumptions, including those of simplicity. This draft aims to rectify the proposes a generalized definition of an endpoint, then explores how it can be applied to understanding the architecture of the Internet, specifically [EDITOR'S NOTE: list controversies here]."

I think that this would be stronger if we said something like "reaffirming this principle requires us to re-examine what an endpoint is". That hits the title better.  I'm also not sure that the second paragraph needs its first two sentences.

(Doing the "discuss in issues, suggest in PRs" split here, as in QUIC).

**Comment by britram** [comment]
seems reasonable to me...
